# Generated by Django 4.2 on 2023-07-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='guest_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='double_bed_room_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='single_bed_room_type',
        ),
    ]
