# Generated by Django 4.2 on 2023-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_rename_name_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
