# Generated by Django 4.2 on 2023-07-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0003_alter_booking_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_name',
            new_name='name',
        ),
    ]
