# Generated by Django 4.2 on 2023-07-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0004_rename_guest_name_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='guest_name',
        ),
    ]
