# Generated by Django 4.2 on 2023-07-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0005_rename_name_booking_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=255),
        ),
    ]
