# Generated by Django 4.2 on 2023-07-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0006_alter_booking_guest_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
    ]
